

service: PythonXSLT # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7

  environment:
    # This will define an environment variable BUCKET with the name of the bucket created on line 68
    BUCKET:
      Ref: S3BucketState

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
          - "*"

functions:
  transxslt:
    handler: runner.transxslt
    events:
      - http:
          path: trans
          method: post

#This creates an s3 bucket
resources:
  Resources:
    S3BucketState:
      Type: AWS::S3::Bucket

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true